In [35]:
import sys

print(sys.version)
print(sys.version_info)

3.8.8 (default, Apr 13 2021, 12:59:45)
[Clang 10.0.0 ]
sys.version_info(major=3, minor=8, micro=8, releaselevel='final', serial=0)

In [26]:
import pandas as pd

#LOads the survey file
df = pd.read_csv("/Users/sirisha/Desktop/Pandas_demo/data/survey_results_public.csv", index_col = 'ResponseId')

#Loads the schema file
schema_df = pd.read_csv("/Users/sirisha/Desktop/Pandas_demo/data/survey_results_schema.csv")


#Rows * Columns
df.shape

#Verify the Dtype and column details
df.info()
df.dtypes
#df

<class 'pandas.core.frame.DataFrame'>
Int64Index: 83439 entries, 1 to 83439
Data columns (total 47 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   MainBranch                    83439 non-null  object
 1   Employment                    83323 non-null  object
 2   Country                       83439 non-null  object
 3   US_State                      14920 non-null  object
 4   UK_Country                    4418 non-null   object
 5   EdLevel                       83126 non-null  object
 6   Age1stCode                    83243 non-null  object
 7   LearnCode                     82963 non-null  object
 8   YearsCode                     81641 non-null  object
 9   YearsCodePro                  61216 non-null  object
 10  DevType                       66484 non-null  object
 11  OrgSize                       60726 non-null  object
 12  Currency                      61080 non-null  object
 13  CompTotal                     47183 non-null  float64
 14  CompFreq                      52150 non-null  object
 15  LanguageHaveWorkedWith        82357 non-null  object
 16  LanguageWantToWorkWith        76821 non-null  object
 17  DatabaseHaveWorkedWith        69546 non-null  object
 18  DatabaseWantToWorkWith        58299 non-null  object
 19  PlatformHaveWorkedWith        52135 non-null  object
 20  PlatformWantToWorkWith        41619 non-null  object
 21  WebframeHaveWorkedWith        61707 non-null  object
 22  WebframeWantToWorkWith        52095 non-null  object
 23  MiscTechHaveWorkedWith        47055 non-null  object
 24  MiscTechWantToWorkWith        38021 non-null  object
 25  ToolsTechHaveWorkedWith       72537 non-null  object
 26  ToolsTechWantToWorkWith       65480 non-null  object
 27  NEWCollabToolsHaveWorkedWith  81234 non-null  object
 28  NEWCollabToolsWantToWorkWith  73022 non-null  object
 29  OpSys                         83294 non-null  object
 30  NEWStuck                      83052 non-null  object
 31  NEWSOSites                    83171 non-null  object
 32  SOVisitFreq                   82413 non-null  object
 33  SOAccount                     82525 non-null  object
 34  SOPartFreq                    67553 non-null  object
 35  SOComm                        82319 non-null  object
 36  NEWOtherComms                 82828 non-null  object
 37  Age                           82407 non-null  object
 38  Gender                        82286 non-null  object
 39  Trans                         80678 non-null  object
 40  Sexuality                     73366 non-null  object
 41  Ethnicity                     79464 non-null  object
 42  Accessibility                 77603 non-null  object
 43  MentalHealth                  76920 non-null  object
 44  SurveyLength                  81711 non-null  object
 45  SurveyEase                    81948 non-null  object
 46  ConvertedCompYearly           46844 non-null  float64
dtypes: float64(2), object(45)
memory usage: 30.6+ MB

MainBranch                       object
Employment                       object
Country                          object
US_State                         object
UK_Country                       object
EdLevel                          object
Age1stCode                       object
LearnCode                        object
YearsCode                        object
YearsCodePro                     object
DevType                          object
OrgSize                          object
Currency                         object
CompTotal                       float64
CompFreq                         object
LanguageHaveWorkedWith           object
LanguageWantToWorkWith           object
DatabaseHaveWorkedWith           object
DatabaseWantToWorkWith           object
PlatformHaveWorkedWith           object
PlatformWantToWorkWith           object
WebframeHaveWorkedWith           object
WebframeWantToWorkWith           object
MiscTechHaveWorkedWith           object
MiscTechWantToWorkWith           object
ToolsTechHaveWorkedWith          object
ToolsTechWantToWorkWith          object
NEWCollabToolsHaveWorkedWith     object
NEWCollabToolsWantToWorkWith     object
OpSys                            object
NEWStuck                         object
NEWSOSites                       object
SOVisitFreq                      object
SOAccount                        object
SOPartFreq                       object
SOComm                           object
NEWOtherComms                    object
Age                              object
Gender                           object
Trans                            object
Sexuality                        object
Ethnicity                        object
Accessibility                    object
MentalHealth                     object
SurveyLength                     object
SurveyEase                       object
ConvertedCompYearly             float64
dtype: object

In [3]:
#ALter the no of column display
pd.set_option('display.max_columns',45)

#Sorting by index
df.sort_index(inplace = True)


# to get the consolidated data on a paticular column 
df['SurveyEase'].value_counts()

Easy                          63087
Neither easy nor difficult    18091
Difficult                       770
Name: SurveyEase, dtype: int64

In [4]:
# Displays the list of columns
df.columns

Index(['MainBranch', 'Employment', 'Country', 'US_State', 'UK_Country',
       'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
       'DevType', 'OrgSize', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [5]:
df.loc[0:5,'DevType':'CompFreq']

,DevType,OrgSize,Currency,CompTotal,CompFreq
ResponseId,,,,,
1,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly
5,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN

In [6]:
schema_df.columns


df['NEWCollabToolsHaveWorkedWith'].value_counts()

Visual Studio Code                                                                                      6700
Visual Studio;Visual Studio Code                                                                        3357
Notepad++;Visual Studio;Visual Studio Code                                                              2382
Vim;Visual Studio Code                                                                                  1527
IntelliJ;Visual Studio Code                                                                             1378
                                                                                                        ...
Eclipse;IntelliJ;Rider;Sublime Text;Vim;Xcode                                                              1
Atom;IPython/Jupyter;Notepad++;Sublime Text;Vim;Visual Studio;Visual Studio Code                           1
Android Studio;Eclipse;IntelliJ;Notepad++;PHPStorm;PyCharm;Rider;Sublime Text;Visual Studio;Webstorm       1
Eclipse;IntelliJ;Notepad++;RStudio;Visual Studio;Visual Studio Code                                        1
Android Studio;PHPStorm;PyCharm;Visual Studio;Xcode                                                        1
Name: NEWCollabToolsHaveWorkedWith, Length: 12100, dtype: int64

In [8]:
countries  = ['Canada','India']

filt = df['Country'].isin(countries)

# df.loc[filt,'DevType'].str.contains('Developer', na = False)

df[filt]

,MainBranch,Employment,Country,US_State,UK_Country,EdLevel,Age1stCode,LearnCode,YearsCode,YearsCodePro,DevType,OrgSize,Currency,CompTotal,CompFreq,LanguageHaveWorkedWith,LanguageWantToWorkWith,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,PlatformHaveWorkedWith,PlatformWantToWorkWith,WebframeHaveWorkedWith,...,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,OpSys,NEWStuck,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOComm,NEWOtherComms,Age,Gender,Trans,Sexuality,Ethnicity,Accessibility,MentalHealth,SurveyLength,SurveyEase,ConvertedCompYearly
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
9,I am a developer by profession,Employed part-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,Coding Bootcamp,6,4,"Developer, front-end","10,000 or more employees",INR\tIndian rupee,NaN,Monthly,HTML/CSS;JavaScript,HTML/CSS;JavaScript,PostgreSQL,PostgreSQL,AWS,NaN,Django;FastAPI,...,Docker;Git,Docker;Git;Kubernetes,PyCharm;Sublime Text,PyCharm;Sublime Text,Windows,Visit Stack Overflow;Google it;Panic,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,"Yes, definitely",No,25-34 years old,Man,No,NaN,South Asian,NaN,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
18,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,9,6,"Developer, front-end;Developer, full-stack;Dev...",500 to 999 employees,CAD\tCanadian dollar,61000.0,Yearly,Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL,Bash/Shell;HTML/CSS;JavaScript;PHP;Ruby;SQL,MySQL;PostgreSQL,MySQL,AWS,NaN,jQuery;Laravel;Ruby on Rails,...,Git,Git,Sublime Text;Visual Studio Code,Visual Studio Code,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,46135.0
23,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,Some college/university study without earning ...,5 - 10 years,School;Friend or family member,7,NaN,NaN,NaN,NaN,NaN,NaN,C#;HTML/CSS;Python,Java;Kotlin;Python,NaN,NaN,NaN,NaN,NaN,...,Unity 3D,NaN,Android Studio,Android Studio,Windows,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",No,Under 18 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
40,I am a student who is learning to code,"Student, part-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School,3,NaN,NaN,NaN,NaN,NaN,NaN,C;C#;C++;HTML/CSS;JavaScript;Node.js;Python,NaN,MongoDB,NaN,Heroku,NaN,Express;jQuery;React.js,...,Flow;Unity 3D,NaN,IPython/Jupyter;Sublime Text;Visual Studio Code,NaN,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,A few times per month or weekly,"Yes, somewhat",Yes,18-24 years old,Woman,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,NaN
50,I am a student who is learning to code,"Student, full-time",India,NaN,NaN,Some college/university study without earning ...,11 - 17 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C;HTML/CSS;Java;JavaScript;Kotlin;Node.js;Pyth...,Dart;Elixir;Go;SQL,NaN,NaN,Heroku,NaN,Django;Express;React.js,...,Git;Yarn,NaN,Android Studio;Atom;Notepad++;Sublime Text;Vis...,NaN,Windows,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow,Multiple times per day,Yes,A few times per week,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83411,I am a student who is learning to code,"Student, part-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,"Other online resources (ex: videos, blogs, etc)",1,NaN,NaN,NaN,NaN,NaN,NaN,C++;JavaScript;Python;TypeScript,C++;JavaScript;Python;TypeScript,MongoDB;PostgreSQL;SQLite,MongoDB;PostgreSQL;SQLite,Heroku,Heroku,Express;React.js,...,Docker;Git;Unreal Engine,Docker;Git;Unreal Engine,Android Studio;Atom;Eclipse;IntelliJ;IPython/J...,IPython/Jupyter;PyCharm;Vim;Visual Studio;Visu...,Windows,Google it;Panic,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,I don't know,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,NaN
83412,I am a developer by profession,Employed full-time,India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",8,5,"Developer, back-end",100 to 499 employees,INR\tIndian rupee,3500000.0,Yearly,Java;JavaScript;SQL,Go;Java;Kotlin;Node.js;SQL,MySQL,Cassandra;Elasticsearch;Redis,AWS,AWS;Google Cloud Platform,Spring,...,Docker;Git,Ansible;Docker;Git;Kubernetes;Terraform,Eclipse;Sublime Text;Visual Studio Code,Eclipse;IntelliJ;Sublime Text,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange;Stack Overflow f...,Daily or almost daily,Yes,Less than once per month or monthly,"Yes, somewhat",No,25-34 years old,Man,No,Straight / Heterosexual,South Asian,None of the above,None of the above,Appropriate in length,Easy,48866.0
83418,I am a developer by profession,"Student, full-time",India,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,School;Friend or family member;Online Courses ...,3,NaN,NaN,NaN,NaN,NaN,NaN,Bash/Shell;C;C++;Java;SQL,Bash/Shell;C++;SQL,PostgreSQL;SQLite,PostgreSQL,AWS,Google Cloud Platform;Microsoft Azure,Spring,...,Docker;Git,Docker;Git,IntelliJ;Vim;Visual Studio Code,IntelliJ;Vim;Visual Studio Code,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange;Stack Overflow f...,Multiple times per day,Yes,Daily or almost daily,"Yes, definitely",Yes,18-24 years old,Man,No,NaN,South Asian,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN
83433,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",18 - 24 years,School,5,Less than 1 year,"Developer, back-end","10,000 or more employees",CAD\tCanadian dollar,106000.0,Yearly,Ruby,Java;Ruby;TypeScript,MySQL;PostgreSQL,NaN,Google Cloud Platform;Heroku,NaN,Flask;React.js;Ruby on Rails;Vue.js,...,Docker;Git;Kubernetes;Yarn,NaN,Atom;IPython/Jupyter;Vim;Visual Studio Code,NaN,MacOS,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,No,NaN,"No, not really",No,18-24 years old,Woman,No,Straight / Heterosexual,East Asian,None of the above,None of the above,Appropriate in length,Easy,80169.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,...,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0

In [10]:
df.columns

Index(['MainBranch', 'Employment', 'Country', 'US_State', 'UK_Country',
       'EdLevel', 'Age1stCode', 'LearnCode', 'YearsCode', 'YearsCodePro',
       'DevType', 'OrgSize', 'Currency', 'CompTotal', 'CompFreq',
       'LanguageHaveWorkedWith', 'LanguageWantToWorkWith',
       'DatabaseHaveWorkedWith', 'DatabaseWantToWorkWith',
       'PlatformHaveWorkedWith', 'PlatformWantToWorkWith',
       'WebframeHaveWorkedWith', 'WebframeWantToWorkWith',
       'MiscTechHaveWorkedWith', 'MiscTechWantToWorkWith',
       'ToolsTechHaveWorkedWith', 'ToolsTechWantToWorkWith',
       'NEWCollabToolsHaveWorkedWith', 'NEWCollabToolsWantToWorkWith', 'OpSys',
       'NEWStuck', 'NEWSOSites', 'SOVisitFreq', 'SOAccount', 'SOPartFreq',
       'SOComm', 'NEWOtherComms', 'Age', 'Gender', 'Trans', 'Sexuality',
       'Ethnicity', 'Accessibility', 'MentalHealth', 'SurveyLength',
       'SurveyEase', 'ConvertedCompYearly'],
      dtype='object')

In [23]:
df.columns = [x.upper() for x in df.columns]
df
df.rename(columns= {'DEVTYPE':'dev'}, inplace = True)

df

,MAINBRANCH,EMPLOYMENT,COUNTRY,US_STATE,UK_COUNTRY,EDLEVEL,AGE1STCODE,LEARNCODE,YEARSCODE,YEARSCODEPRO,dev,ORGSIZE,CURRENCY,COMPTOTAL,COMPFREQ,LANGUAGEHAVEWORKEDWITH,LANGUAGEWANTTOWORKWITH,DATABASEHAVEWORKEDWITH,DATABASEWANTTOWORKWITH,PLATFORMHAVEWORKEDWITH,PLATFORMWANTTOWORKWITH,WEBFRAMEHAVEWORKEDWITH,...,TOOLSTECHHAVEWORKEDWITH,TOOLSTECHWANTTOWORKWITH,NEWCOLLABTOOLSHAVEWORKEDWITH,NEWCOLLABTOOLSWANTTOWORKWITH,OPSYS,NEWSTUCK,NEWSOSITES,SOVISITFREQ,SOACCOUNT,SOPARTFREQ,SOCOMM,NEWOTHERCOMMS,AGE,GENDER,TRANS,SEXUALITY,ETHNICITY,ACCESSIBILITY,MENTALHEALTH,SURVEYLENGTH,SURVEYEASE,CONVERTEDCOMPYEARLY
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Slovakia,NaN,NaN,"Secondary school (e.g. American high school, G...",18 - 24 years,Coding Bootcamp;Other online resources (ex: vi...,NaN,NaN,"Developer, mobile",20 to 99 employees,EUR European Euro,4800.0,Monthly,C++;HTML/CSS;JavaScript;Objective-C;PHP;Swift,Swift,PostgreSQL;SQLite,SQLite,NaN,NaN,Laravel;Symfony,...,NaN,NaN,PHPStorm;Xcode,Atom;Xcode,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Multiple times per day,Yes,A few times per month or weekly,"Yes, definitely",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,62268.0
2,I am a student who is learning to code,"Student, full-time",Netherlands,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",7,NaN,NaN,NaN,NaN,NaN,NaN,JavaScript;Python,NaN,PostgreSQL,NaN,NaN,NaN,Angular;Flask;Vue.js,...,Docker;Git;Yarn,Git,Android Studio;IntelliJ;Notepad++;PyCharm,NaN,Windows,Visit Stack Overflow;Google it,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,"Yes, definitely",No,18-24 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,None of the above,Appropriate in length,Easy,NaN
3,"I am not primarily a developer, but I write co...","Student, full-time",Russian Federation,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Assembly;C;Python;R;Rust,Julia;Python;Rust,SQLite,SQLite,Heroku,NaN,Flask,...,NaN,NaN,IPython/Jupyter;PyCharm;RStudio;Sublime Text;V...,IPython/Jupyter;RStudio;Sublime Text;Visual St...,MacOS,Visit Stack Overflow;Google it;Watch help / tu...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,"Yes, definitely",Yes,18-24 years old,Man,No,Prefer not to say,Prefer not to say,None of the above,None of the above,Appropriate in length,Easy,NaN
4,I am a developer by profession,Employed full-time,Austria,NaN,NaN,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",11 - 17 years,NaN,NaN,NaN,"Developer, front-end",100 to 499 employees,EUR European Euro,NaN,Monthly,JavaScript;TypeScript,JavaScript;TypeScript,NaN,NaN,NaN,NaN,Angular;jQuery,...,NaN,NaN,NaN,NaN,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,Daily or almost daily,Yes,Daily or almost daily,Neutral,No,35-44 years old,Man,No,Straight / Heterosexual,White or of European descent,I am deaf / hard of hearing,NaN,Appropriate in length,Neither easy nor difficult,NaN
5,I am a developer by profession,"Independent contractor, freelancer, or self-em...",United Kingdom of Great Britain and Northern I...,NaN,England,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",5 - 10 years,Friend or family member,17,10,"Developer, desktop or enterprise applications;...","Just me - I am a freelancer, sole proprietor, ...",GBP\tPound sterling,NaN,NaN,Bash/Shell;HTML/CSS;Python;SQL,Bash/Shell;HTML/CSS;Python;SQL,Elasticsearch;PostgreSQL;Redis,Cassandra;Elasticsearch;PostgreSQL;Redis,NaN,NaN,Flask,...,Docker;Git;Kubernetes;Yarn,Docker;Git;Kubernetes;Yarn,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim,Atom;IPython/Jupyter;Notepad++;PyCharm;Vim;Vis...,Linux-based,Visit Stack Overflow;Go for a walk or other ph...,Stack Overflow;Stack Exchange,Daily or almost daily,Yes,A few times per week,"Yes, somewhat",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,NaN,Appropriate in length,Easy,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83435,I am a developer by profession,Employed full-time,United States of America,Texas,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",6,5,"Developer, back-end",20 to 99 employees,USD\tUnited States dollar,160500.0,Yearly,Clojure;Kotlin;SQL,Clojure,Oracle;SQLite,SQLite,AWS,AWS,NaN,...,Docker;Git,Git;Kubernetes,IntelliJ;Sublime Text;Vim;Visual Studio Code,Sublime Text;Vim,MacOS,Call a coworker or friend;Google it,Stack Overflow;Stack Exchange,A few times per week,No,NaN,"No, not at all",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a concentration and/or memory disorder ...,Appropriate in length,Easy,160500.0
83436,I am a developer by profession,"Independent contractor, freelancer, or self-em...",Benin,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,"Other online resources (ex: videos, blogs, etc...",4,2,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",XOF\tWest African CFA franc,200000.0,Monthly,NaN,NaN,Firebase;MariaDB;MySQL;PostgreSQL;Redis;SQLite,Firebase;MariaDB;MongoDB;MySQL;PostgreSQL;Redi...,NaN,NaN,Django;jQuery;Laravel;React.js;Ruby on Rails,...,Git;Unity 3D;Unreal Engine,Docker;Git;Kubernetes,Android Studio;Eclipse;Emacs;IntelliJ;NetBeans...,Emacs;IntelliJ;PHPStorm;PyCharm;RStudio;Sublim...,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,Multiple times per day,Yes,I have never participated in Q&A on Stack Over...,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Black or of African descent,None of the above,None of the above,Appropriate in length,Easy,3960.0
83437,I am a developer by profession,Employed full-time,United States of America,New Jersey,NaN,"Secondary school (e.g. American high school, G...",11 - 17 years,School,10,4,Data scientist or machine learning specialist;...,"10,000 or more employees",USD\tUnited States dollar,1800.0,Weekly,Groovy;Java;Python,Java;Python,DynamoDB;Elasticsearch;MongoDB;PostgreSQL;Redis,DynamoDB;Redis,AWS;Google Cloud Platform,AWS,FastAPI;Flask,...,Ansible;Docker;Git;Terraform,Docker;Git;Kubernetes;Terraform,Android Studio;Eclipse;IntelliJ;IPython/Jupyte...,IntelliJ;IPython/Jupyter;Notepad++;Vim,Windows,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange,A few times per week,Yes,I have never participated in Q&A on Stack Over...,"No, not really",No,25-34 years old,Man,No,NaN,White or of European descent,None of the above,None of the above,Appropriate in length,Neither easy nor difficult,90000.0
83438,I am a developer by profession,Employed full-time,Canada,NaN,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",11 - 17 years,Online Courses or Certification;Books / Physic...,5,3,"Developer, back-end",20 to 99 employees,CAD\tCanadian dollar,90000.0,Monthly,Bash/Shell;JavaScript;Node.js;Python,Go;Rust,Cassandra;Elasticsearch;MongoDB;PostgreSQL;Redis,NaN,Heroku,AWS;DigitalOcean,Django;Express;Flask;React.js,...,Ansible;Docker;Git;Terraform,Kubernetes;Terraform,PyCharm;Sublime Text,NaN,MacOS,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow,A few times per month or weekly,Yes,Less than once per month or monthly,"No, not really",No,25-34 years old,Man,No,Straight / Heterosexual,White or of European descent,None of the above,I have a mood or emotional disorder (e.g. depr...,Appropriate in length,Neither easy nor difficult,816816.0
83439,I am a developer by profession,Employed full-time,Brazil,NaN,NaN,"Professional degree (JD, MD, etc.)",11 - 17 years,School,14,4,"Developer, front-end;Developer, full-stack;Dev...",I don’t know,BRL\tBrazilian real,7700.0,Monthly,Delphi;Elixir;HTML/CSS;Java;JavaScript,Elixir;HTML/CSS;Java;JavaScript;Node.js;PHP;SQ...,Oracle;PostgreSQL,Elasticsearch;MongoDB;MySQL;Oracle;PostgreSQL;...,Microsoft Azure,AWS,Angular;Spring,...,Docker;Git,Docker;Git;Kubernetes,IntelliJ;Visual Studio Code,IntelliJ;PHPStorm;Visual Studio Code,Linux-based,Call a coworker or friend;Visit Stack Overflow...,Stack Overflow;Stack Exchange;Stack Overflow f...,A few times per week,Yes,A few times per week,"Yes, somewhat",No,18-24 years old,Man,No,Straight / Heterosexual,Hispanic or Latino/a/x,None of the above,None of the above,Appropriate in length,Easy,21168.0

In [9]:
filt = (df['CompTotal'] > 5000) & (df['CompFreq'] == 'Monthly')

df.loc[filt,['Country','DevType','CompFreq','CompTotal']]

,Country,DevType,CompFreq,CompTotal
ResponseId,,,,
10,Sweden,Data scientist or machine learning specialist,Monthly,42000.0
17,Turkey,"Developer, full-stack",Monthly,9000.0
19,Singapore,NaN,Monthly,18700.0
30,Russian Federation,"Developer, desktop or enterprise applications;...",Monthly,200000.0
32,Israel,"Engineer, data;Developer, back-end",Monthly,35000.0
...,...,...,...,...
83429,Brazil,"Senior Executive (C-Suite, VP, etc.)",Monthly,15000.0
83432,Pakistan,"Developer, mobile;Developer, desktop or enterp...",Monthly,150000.0
83436,Benin,"Developer, full-stack",Monthly,200000.0
83438,Canada,"Developer, back-end",Monthly,90000.0
83439,Brazil,"Developer, front-end;Developer, full-stack;Dev...",Monthly,7700.0